### PR TITLE
Selected menu

### PR DESCRIPTION
**Pull request by hallykeeg**
Add a dynamic styling to differentiate selected menu item from the others. 
Currently, there is no sign showing which menu item is associated with the current view rendered. 
 
Since tests are not OK yet, the PR might require more time to be evaluated and eventually  merged. 

selected

### CODE REVIEW

**Comment by Ducasse** [comment]
The changes looks ok to me. Let us wait to see.

**Comment by Ducasse** [comment]
@jccfd it looks ok to me but I prefer that you have a look and tell us.

**Comment by jecisc** [comment]
Sorry I didn't had the notification enabled. I'll look at it soon

**Comment by jccfd** [comment]
Sorry I didn't had the notifications enabled. I'll look at it soon

**Review by jecisc — APPROVED** [review]
This works fine.

Maybe we can improve a little the menu management to simplify it a little but it would require much more work and this current solution does the work.

**Pull request merged**
